### ISSUE TITLE
What is the machine requirement for training?

### ISSUE THREAD

**Issue by ievn2015** [StanfordVL/iGibsonChallenge2021#1]

**Comment by ievn2015** [comment]
I noticed that "The full training takes around 100G CPU memory and 10G GPU memory." May I know for a complete entry, what is the basic hardware requirements for training? Thank you.

**Comment by ChengshuLi** [comment]
Hi, the full training means that you instantiate eight parallel environments (each environment uses one of the training scenes). It should take around 100G CPU memory and 10G GPU memory. 

Does this answer your question? Feel free to clarify what you mean by "a complete entry". Thanks!

**Comment by ievn2015** [comment]
Thanks
