### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pyrvo2 (unavailable) (from gibson2) ERROR: No matching distribution found for pyrvo2 (unavailable)

### ISSUE THREAD

**Issue by G-KUMAR** [StanfordVL/iGibsonChallenge2021#10]
Getting Error while installing with "Not Using Docker" i.e. using Anaconda while running "pip install -e ." command on ubuntu 16.04 CUDA 10.0 and cudnn 7.6.5.

**Comment by ChengshuLi** [comment]
Please kindly copy the entire error trace when you do `pip install -e .` for iGibson.

One thing you can try to do is to install Python-RVO2 from source in the same conda environment: https://github.com/sybrenstuvel/Python-RVO2/. After installation is done, you should be able to `import rvo2` in your conda environment. Thanks.

**Comment by G-KUMAR** [comment]
Sorry, the error was due to error in installation of "Cython". 

"pip install cython"  and then trying "pip install -e ." solved the issue.

Thanks for the prompt reply,
