### ISSUE TITLE
Broken pipe error using docker

### ISSUE THREAD

**Issue by wzx16** [StanfordVL/iGibsonChallenge2021#13]
Hi, I used the original docker to train a SAC agent, but I got a broken error while training. Can you help me with this issue?

> I0520 11:37:22.428182 140700759025472 mesh_renderer_cpu.py:335] Loading /opt/iGibson/gibson2/data/assets/models/person_meshes/person_2/meshes/person.obj
> I0520 11:37:23.353936 140700759025472 parallel_py_environment.py:89] All processes started.
> Traceback (most recent call last):
>   File "train_eval.py", line 596, in <module>
>     app.run(main)
>   File "/miniconda/envs/gibson/lib/python3.6/site-packages/absl/app.py", line 303, in run
>     _run_main(main, args)
>   File "/miniconda/envs/gibson/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "train_eval.py", line 589, in main
>     model_ids_eval=FLAGS.model_ids_eval,
>   File "/miniconda/envs/gibson/lib/python3.6/site-packages/gin/config.py", line 1032, in wrapper
>     utils.augment_exception_message_and_reraise(e, err_str)
>   File "/miniconda/envs/gibson/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
>     six.raise_from(proxy.with_traceback(exception.__traceback__), None)
>   File "<string>", line 3, in raise_from
>   File "/miniconda/envs/gibson/lib/python3.6/site-packages/gin/config.py", line 1009, in wrapper
>     return fn(*new_args, **new_kwargs)
>   File "train_eval.py", line 239, in train_eval
>     parallel_py_environment.ParallelPyEnvironment(tf_py_env))
>   File "/miniconda/envs/gibson/lib/python3.6/site-packages/gin/config.py", line 1032, in wrapper
>     utils.augment_exception_message_and_reraise(e, err_str)
>   File "/miniconda/envs/gibson/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
>     six.raise_from(proxy.with_traceback(exception.__traceback__), None)
>   File "<string>", line 3, in raise_from
>   File "/miniconda/envs/gibson/lib/python3.6/site-packages/gin/config.py", line 1009, in wrapper
>     return fn(*new_args, **new_kwargs)
>   File "/opt/agents/tf_agents/environments/parallel_py_environment.py", line 75, in __init__
>     if any(env.action_spec() != self._action_spec for env in self._envs):
>   File "/opt/agents/tf_agents/environments/parallel_py_environment.py", line 75, in <genexpr>
>     if any(env.action_spec() != self._action_spec for env in self._envs):
>   File "/opt/agents/tf_agents/environments/parallel_py_environment.py", line 250, in action_spec
>     self._action_spec = self.call('action_spec')()
>   File "/opt/agents/tf_agents/environments/parallel_py_environment.py", line 285, in call
>     self._conn.send((self._CALL, payload))
>   File "/miniconda/envs/gibson/lib/python3.6/multiprocessing/connection.py", line 206, in send
>     self._send_bytes(_ForkingPickler.dumps(obj))
>   File "/miniconda/envs/gibson/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
>     self._send(header + buf)
>   File "/miniconda/envs/gibson/lib/python3.6/multiprocessing/connection.py", line 368, in _send
>     n = write(self._handle, buf)
> BrokenPipeError: [Errno 32] Broken pipe
>   In call to configurable 'ParallelPyEnvironment' (<function ParallelPyEnvironment.__init__ at 0x7ff6a7e94d08>)
>   In call to configurable 'train_eval' (<function train_eval at 0x7ff6c1b1dbf8>)
> ******************PyBullet Logging Information:
> PyBullet Logging Information******************

**Comment by ChengshuLi** [comment]
Hmmm does this happen at the beginning of training or in the middle of training (for how long?). I wonder whether this is due to CPU OOM.

**Comment by wzx16** [comment]
In the middle of training. I think it's after the Rs_int scene. I monitored the RAM usage and found all of my RAM space (32GB) was obtained. So I changed the ParallelEnvironment's parameter to have the driver run it serially, but the same issue just happened again. I saw the step 7 of README said it will take 100GB CPU memory, do I actually need a 100GB ram machine?

**Comment by ChengshuLi** [comment]
Yes, you actually do need a 100GB RAM machine. I would recommend doing the training on a cloud platform like GCloud, AWS, or Azure.

**Comment by wzx16** [comment]
Ok I see. If I use BatchedPyEnvironment instead of ParallelPyEnvironment, would it reduce the requirement of RAM?

**Comment by ChengshuLi** [comment]
I am not sure because I haven't tried that myself. Feel free to try that out and let me know how it goes.

**Comment by wzx16** [comment]
Just tried the batch environment. It seems no matter what kind of environment was used, all the scenes have to be loaded to RAM (parallel env can only load it faster), so 100GB is mandatory. Can you share some info about your cloud training process (e.g. platform, hardware)? Thank you.

**Comment by ChengshuLi** [comment]
You can try using google cloud with 3 K80 GPUs, 24 cores, and ~150 GB CPU memory

**Comment by wzx16** [comment]
Thanks, closing this issue.
