### ISSUE TITLE
get stuck when evaluate multi checkpoint

### ISSUE THREAD

**Issue by yestinl** [StanfordVL/iGibsonChallenge2021#14]
I want to check the performance on different checkpoint. And I run the following same script but different gpus and different checkpoints by modifying the first line of "checkpoint" file in policy directory.   

`export CONFIG_FILE=/opt/igibson/gibson2/examples/configs/locobot_interactive_nav.yaml; export TASK=interactive; export SPLIT=minival; export EPISODE_DIR=/opt/igibson/gibson2/data/episodes_data/interactive_nav; CUDA_VISIBLE_DEVICES=1 python agent.py --agent-class SAC --ckpt-path /opt/agents/tf_agents/agents/sac/examples/v1/test`

But I got stuck in the segmentation fault.
![image](https://user-images.githubusercontent.com/27557933/119234715-de41ad00-bb61-11eb-8868-77695c0b136d.png)

By the way, I notice that the results are wrote to tensorboard, but I found it hard to forward port of tensorboard in a docker container. Could you provide a more convenient way to track different checkpoint of the model like visualizing in the tensorboard file or read the tensorboard?

**Comment by ChengshuLi** [comment]
Please kindly forward me a minimal repro script for this issue and provide more details about your system. It seems that I cannot reproduce your issue on my side.

For tensorboard, you can mount a local directory, e.g. ` docker run --name <docker image name> -v ~/result:/result ...`
and then run `docker exec -it <docker image name> tensorboard --logdir /result`. You also need to set up the network firewall rules if you are using cloud platforms.
