### ISSUE TITLE
If there any Suggestions for the training on GeForce RTX 30XX Graphics Card

### ISSUE THREAD

**Issue by ievn2015** [StanfordVL/iGibsonChallenge2021#3]
Hi,
I tried to install `tensorflow-gpu==1.15.0` through a wheel package on my GeForce RTX 3070 and 3090
[](https://developer.nvidia.com/blog/accelerating-tensorflow-on-a100-gpus/)(https://developer.nvidia.com/blog/accelerating-tensorflow-on-a100-gpus/)
But it seems unable to complete the training with CUDA.

Then I tried to install `tensorflow-gpu==2.4.0`, because I want to use CUDA on my GeForce RTX 3070 and 3090,
It seems that I need to use TF-agent v0.6.0.

I  worry about whether the Online submission can be completed, if I use `tensorflow-gpu==2.4.0` together with TF-agent v0.6.0.

I want to try the starter code with  `tensorflow-gpu==1.15.0` with  TF-agent v0.3.0 on my  GeForce RTX 3070 and 3090
So, Could you please give me some Suggestions?
Thank you in advance for your help

**Comment by ievn2015** [comment]
It seems unable to complete the training with CUDA using docker on GeForce RTX 3070

**Comment by ChengshuLi** [comment]
Are you able to use `tensorflow-gpu==1.15.0` in docker with your GPU? In other words, are you able to run `./test_minival_locally.sh --docker-name my_submission` successfully with your GPU?

**Comment by ievn2015** [comment]
After I run `./test_minival_locally.sh --docker-name my_submission`，the process was killed after Rendering. In other words, I think it can not train and compute. 
The  Memory-Usage is about to 2500MiB, then the process was killed.
`Memory 31.3 GiB`
`Processor Intel i5-10400 CPU@ 2.90GHz x 12`
`OS type 64-bit Ubuntu 18.04.5 LTS`
 `GeForce RTX 3070`
`NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2   `
Some outputs of terminal are as follows.
...
```
...
...
2021-04-01 01:08:33.236681: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5976 MB memory) -> physical GPU (device: 0, name: GeForce RTX 3070, pci bus id: 0000:01:00.0, compute capability: 8.6)`
...
...
I0401 01:13:45.851150 140295497275200 articulated_object.py:621] Resetting URDF to (pos,ori): [0. 0. 0.], [0. 0. 0. 1.]
2021-04-01 01:13:46.663514: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2021-04-01 01:15:08.865661: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
...
...
2021-04-01 01:31:24.278383: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: ptxas exited with non-zero error code 65280, output: ptxas fatal   : Value 'sm_86' is not defined for option 'gpu-name'
...
...
Relying on driver to perform ptx compilation. This message will be only logged once.
I0401 01:31:53.001651 140295497275200 articulated_object.py:621] Resetting URDF to (pos,ori): [0. 0. 0.], [0. 0. 0. 1.]
...
...
I0401 01:33:45.120462 140295497275200 articulated_object.py:621] Resetting URDF to (pos,ori): [0. 0. 0.], [0. 0. 0. 1.]
...
...
I0401 01:34:08.640454 140295497275200 metric_utils.py:47] Step = 0 
		 AverageReturn = -0.5665685534477234
		 AverageEpisodeLength = 500.0
I0401 01:34:08.640782 140295497275200 train_eval.py:462] Global step 0: Running initial collect op.
...
...
I0401 01:34:09.032746 140295497275200 articulated_object.py:621] Resetting URDF to (pos,ori): [0. 0. 0.], [0. 0. 0. 1.]
...
...
```
**Then, the process was killed.**
```
...
...
I0401 01:34:09.032136 140295497275200 articulated_object.py:621] Resetting URDF to (pos,ori): [0. 0. 0.], [0. 0. 0. 1.]
I0401 01:34:09.032442 140295497275200 articulated_object.py:621] Resetting URDF to (pos,ori): [0. 0. 0.], [0. 0. 0. 1.]
I0401 01:34:09.032746 140295497275200 articulated_object.py:621] Resetting URDF to (pos,ori): [0. 0. 0.], [0. 0. 0. 1.]

./train_minival.sh: line 34:     8 Killed                  python -u train_eval.py --root_dir $log_dir --config_file $config_file --initial_collect_steps 500 --collect_steps_per_iteration 1 --batch_size 256 --train_steps_per_iteration 1 --replay_buffer_capacity 10000 --num_eval_episodes 10 --eval_interval 10000000 --gpu_c $gpu_c --gpu_g $gpu_g --num_parallel_environments 1 --model_ids Rs_int
```

**Comment by ievn2015** [comment]
Same situation when I tried to train Not using Docker.
By the way, I am going to buy GeForce RTX 3090 to paticipate iGibsonChallenge2021, I worry about whether I can try the starter code.

**Comment by fxia22** [comment]
RTX 3090 should be fine, we will be distributing a docker image that uses cuda 11.0 and tensorflow 2.4, which should work for your setup.

**Comment by fxia22** [comment]
FYI you can use this docker image to develop based on cuda 11 and tensorflow 2.4, it should work for RTX 30xx setup.

`docker pull gibsonchallenge/gibson_challenge_2021:cuda11_tf24_agents`

**Comment by ChengshuLi** [comment]
Feel free to re-open the issue if you have further questions!
