### ISSUE TITLE
What's the meaning and unit of the variables in the array of task_obs in state

### ISSUE THREAD

**Issue by ievn2015** [StanfordVL/iGibsonChallenge2021#5]

**Comment by ievn2015** [comment]
The following task setup are provided according to the README.md:

`Observation: (1) Goal position relative to the robot in polar coordinates, (2) current linear and angular velocities, (3) RGB+D images.`

I can get the following information for example:

`'task_obs':array([ 2.2312702 ,  1.63387479, -0.08075723, -0.22005186])`

Could you help me find out the meaning and unit of the first two variables so that I can calculate the location of the target.
Thank you!

**Comment by ChengshuLi** [comment]
Hi,

The first variable is the distance to the goal, r. The unit is meter.
The second variable is the angle to the goal, theta. The unit is radian.
More details can be found in https://en.wikipedia.org/wiki/Polar_coordinate_system

You can convert the first two variables from polar coordinate to cartesian coordinate by 
```
x = r * cos(theta)
y = r * sin(theta)
```
Note that these are in agent's local frame with the x-axis pointing forward and the y-axis pointing leftward. 

The third variable is the current linear velocity. The unit is meter/second.
The fourth variable is the current angular velocity. The unit is radian/second

Let me know if this helps.

**Comment by ievn2015** [comment]
Thank you, I got it!
