### ISSUE TITLE
AssertionError while running ./test_minival_locally.sh

### ISSUE THREAD

**Issue by qianqianlo** [StanfordVL/iGibsonChallenge2021#7]
Hi all, I encountered a problem when following 'Local Evaluation' step. When I ran `./test_minival_locally.sh --docker-name my_submission`, it showed the error:
```
INFO:root:Importing iGibson (gibson2 module)
INFO:root:Assets path: /opt/iGibson/gibson2/data/assets
INFO:root:Gibson Dataset path: /opt/iGibson/gibson2/data/g_dataset
INFO:root:iG Dataset path: /opt/iGibson/gibson2/data/ig_dataset
INFO:root:3D-FRONT Dataset path: /opt/iGibson/gibson2/data/threedfront_dataset
INFO:root:CubiCasa5K Dataset path: /opt/iGibson/gibson2/data/cubicasa_dataset
INFO:root:Example path: /opt/iGibson/gibson2/examples
INFO:root:Example config path: /opt/iGibson/gibson2/examples/configs
pybullet build time: Dec 23 2020 01:46:51
torch is not available, falling back to rendering to memory(instead of tensor)
Traceback (most recent call last):
  File "agent.py", line 34, in <module>
    main()
  File "agent.py", line 30, in main
    challenge.submit(agent)
  File "/opt/iGibson/gibson2/challenge/challenge.py", line 33, in submit
    assert os.path.isdir(split_dir)
AssertionError
```
I used the same code shown in the document, but I skipped Step2(Install nvidia-docker2). So, is nvidia-docker2 required? Should I change some parts in the Dockerfile? Thanks!

**Comment by ChengshuLi** [comment]
Could you please add a print statement before this error?
```
print(split_dir)
```

Also, can you check if you have correctly mounted `gibson_challenge_data_2021`?
https://github.com/StanfordVL/iGibsonChallenge2021/blob/bfcc07413e0b9f8282e5c36918ee62b16f050448/test_minival_locally.sh#L23

**Comment by qianqianlo** [comment]
Thanks, the problem's been solved!
