### ISSUE TITLE
Can I modify locobot.urdf in my docker image and  submit for Online submission?

### ISSUE THREAD

**Issue by ievn2015** [StanfordVL/iGibsonChallenge2021#9]
I wonder whether the modified locobot.urdf in my docker image can be loaded  in unseen scenes in your test split in the Online submission.

**Comment by ChengshuLi** [comment]
No, you shouldn't modify locobot.urdf, as it is based on a real robot and shared across all the participants.

**Comment by ChengshuLi** [comment]
Feel free to re-open the issue if you have further questions!
